### ISSUE TITLE
Question: How to access media

### ISSUE THREAD

**Issue by justkidding96** [outl1ne/nova-media-hub#1]
Hi thanks for your package was looking for this kind of package for a long time. I've a question, how can we access the image on the front-end?

**Comment by Tarpsvo** [comment]
When serializing the model in which you have the MediaHub field, you have to format it for the frontend.

I'll be adding more sophisticated formatting support some day, but for now you can do something like this:

```
jsonSerialize() {
  $data = parent::jsonSerialize();
  if (isset($data['media']) $data['media'] = Media::find($data['media']);
  return $data;
}
```
