### ISSUE TITLE
Job to create thumbnails - fail 

### ISSUE THREAD

**Issue by vodnicearv** [outl1ne/nova-media-hub#10]
Error is: Could not find the image `image_name.jpg`.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/14403446/185927067-f5614f7a-2d15-4098-bb50-17cab018febd.png">

**Comment by Tarpsvo** [comment]
Seems as if your media doesn't have a 'disk' defined. Can you check your database and see if there's a 'disk' for media 321.jpg?

**Comment by vodnicearv** [comment]
You can use minio as s3 server

În mie., 24 aug. 2022 la 15:34 Tarvo R. ***@***.***> a scris:

**Comment by Tarpsvo** [comment]
Hi! There was indeed some issues with cloud storage. These should now be resolved in release 1.1.0. I will test it more as well during today and will make more fixes if necessary.

**Comment by vodnicearv** [comment]
nice, wait release
