### ISSUE TITLE
Feature: check for existing items (migrating media to Media Hub)

### ISSUE THREAD

**Issue by nullthoughts** [outl1ne/nova-media-hub#11]
Feature suggestion (although this may be an edge case):

I'm migrating over several thousand images from another app, and wanted to check if an image exists before importing. The following is working, but if others find it useful an `existing` helper method could be implemented (with support for other file instances, eg. UploadedFile/Base64).

```php
return collect($pictures)
    ->reject(function ($picture) {
        return Media::where('original_file_hash', md5_file($picture))->exists();
    })
    ->map(function ($picture) use ($collectionName) {
        return MediaHub::storeMediaFromUrl($picture, $collectionName);
    })
```

If it's something of interest, I can submit a PR.

**Comment by Tarpsvo** [comment]
Heya! The file hash logic was added for this exact reason. I hadn't gotten around to fully implementing it yet, as I had a lot of features in mind and had limited time.

However, I did add this now in release 1.1.0 and it worked like a charm when I tested it. :)
