### ISSUE TITLE
Field is not translatable

### ISSUE THREAD

**Issue by vodnicearv** [outl1ne/nova-media-hub#12]
Field is not compatible with https://github.com/outl1ne/nova-translatable

after submit, data is not saved

**Comment by mastergman87** [comment]
Are you sure it isn't saved to you? For me, the JSON string is successfully stored in the database:

{"en":"1","de":null}

I also work with both packages outl1ne/nova-media-hub 1.1.4 and outl1ne/nova-translatable 2.1.0 in the latest version.

But unfortunately the uploaded result is not displayed after saving. If I then save again with other images, the current ones in the DB are overwritten.

However, it works perfectly for the non-translated images.

Does anybody have the same Problem?

**Comment by Tarpsvo** [comment]
There was indeed an issue with media being resolved when using nova-translatable. Sorry about that! Fixed in version 1.1.5.
