### ISSUE TITLE
field  return id 

### ISSUE THREAD

**Issue by MA7MOUDAL3RABY** [outl1ne/nova-media-hub#14]
i need to overwrite the default function and make the field return full image URL  not the id

**Comment by Tarpsvo** [comment]
You can overwrite both the Model and the Resource.

**Comment by MA7MOUDAL3RABY** [comment]
> 

how?

kindly send me some links.

**Comment by KasparRosin** [comment]
Publish the config and override the 'model' key value.
https://github.com/outl1ne/nova-media-hub#configure
