### ISSUE TITLE
how to customize return value

### ISSUE THREAD

**Issue by MA7MOUDAL3RABY** [outl1ne/nova-media-hub#15]
hi, 
I am using Inertia js, I need to customize the returned value instead of "image id" -> "https://mydomain.com/media"file system drive"/projects"collection name"/project.png"image name not ID"

Is it possible to achieve that?

**Comment by Tarpsvo** [comment]
You can customize your model to overwrite the ID with Media::find($this->id) in the toArray() method for example.
