### ISSUE TITLE
encode issue

### ISSUE THREAD

**Issue by Brand3000** [outl1ne/nova-media-hub#18]
Hi!
Haven't you noticed that the encode function wreak the file path? It changes slashes to %2F in paths. 
Instead of 
return urlencode(urldecode($fileName)); 
I do
return dirname($fileName)."/".urlencode(urldecode(basename($fileName)));

**Comment by KasparRosin** [comment]
Released version 1.2.4 that fixes the issue.
I did indeed include encoding to paths, my mistake. Sorry.
