### ISSUE TITLE
Custom propriety support ?

### ISSUE THREAD

**Issue by mrleblanc101** [outl1ne/nova-media-hub#22]
Would it be possible to add custom propriety to Images, like the "alt" text or the "copyright" from the photographer, etc

**Comment by murdercode** [comment]
Definitely not "the" solution, in my case I needed captioning and copyright. There is a [PR](https://github.com/outl1ne/nova-media-hub/pull/21) about it ;)

**Comment by mrleblanc101** [comment]
@murdercode Instead of hardcoding these 2 fields, we should probably make them configurable. I'd need much more than 2 metadata field.

**Comment by Tarpsvo** [comment]
Hi! I added custom property support in version 1.3.0. You can use it like so:

```php
// NovaServiceProvider.php

public function tools()
{
    return [
        \Outl1ne\NovaMediaHub\MediaHub::make()
            ->withCustomFields([
                'copyright' => __('Copyright'),
                'caption' => __('Caption'),
            ], overwrite: false),
    ];
}
```

Hope this helps. Good luck!
