### ISSUE TITLE
any file validation?

### ISSUE THREAD

**Issue by wjstraver** [outl1ne/nova-media-hub#24]
Hi,

I like this project you've built, but before I can implement it I have a question which I could not find any answers in the documentation or code:

Is there any way to perform validation on the files being uploaded? I would like to limit the filetypes being uploaded, add our own custom file rules, perform virus scan on uploads etc.

As example someone now can easily upload a `test.php` with the following script:
```php
<?php

echo phpinfo();
```

after uploading and the uploading folder is set to public, anyone can go to the url of that file and get all php info of the server.

If it doesn't exist yet, it would be awesome to add in the `config/nova-media-hub.php` something like the following:

```php
return [
    //...

    'file_validation' => [
        '*' => [ // any collection
            'file',
            'max:5000',
            'mimes:doc,xls,jpg,png,svg,pdf'
            MyCustomRule::class,
            // array of validation rules like you would normally have in laravel
        ],
        'images' => [ // validation just for this collection
             'image'
        ]
    ]
];
```

**Comment by murdercode** [comment]
I can confirm a **File Upload (Authenticated)** vulnerability.
I propose this [PR](https://github.com/outl1ne/nova-media-hub/pull/26) as a quick solution.

**Comment by Tarpsvo** [comment]
Heya @murdercode! Thanks for your report and PR. :) I added a new feature called FileValidator in version 1.4.0. It's a class just like FileNamer and PathMaker and you can override it in the config (nova-media-hub.file_validator). You can code your validation logic there. This should give the user more freedom than just a config option with a list of rules. It's also easier for me to maintain.

See the source for the default FileValidator here:
https://github.com/outl1ne/nova-media-hub/blob/main/src/MediaHandler/Support/FileValidator.php

Thanks again and good luck! Hope this fits your needs.
