### ISSUE TITLE
Behavior concern: delete file on copyFileToMediaLibrary

### ISSUE THREAD

**Issue by NessterGit** [outl1ne/nova-media-hub#30]
Hi, thanks for the great package ! 

I'm using your MediaHub::fileHandler to seed a new database from existing files. 
```
MediaHub::fileHandler()            
    ->withFile($questions_audios->path($question['id_audio_fr'] . '.mp3'))
    ->withCollection('question_audio')
    ->save();
```
But the save() method deletes the original files by default:
`$this->filesystem->copyFileToMediaLibrary($this->pathToFile, $media, $this->fileName, Filesystem::TYPE_ORIGINAL, **true**);`

I'm wondering if this is the wanted behavior and if it should not be false by default ? I didn't lose any files but can imagine someone getting bit by this particular situation. 

If this is the desired behavior on your side, should it be possible to modify it slightly to delete but on demand ? Like maybe :
```
protected string $removeOnSave = false;

public function removeOnSave(bool $removeOnSave)
{
    $this->removeOnSave = $removeOnSave;
    return $this;
}

$this->filesystem->copyFileToMediaLibrary($this->pathToFile, $media, $this->fileName, Filesystem::TYPE_ORIGINAL, $this->removeOnSave);
```
Then we could use it like this:
```
MediaHub::fileHandler()            
    ->withFile($questions_audios->path($question['id_audio_fr'] . '.mp3'))
    ->withCollection('question_audio')
    **->removeOnSave(true)**
    ->save();
```

Cheers !

**Comment by Tarpsvo** [comment]
Heya! I added a new option `deleteOriginal()` to FileHandler which is now false by default. It's available on version 1.5.0. Good luck!
