### ISSUE TITLE
How to generate all sizes? Using S3

### ISSUE THREAD

**Issue by renege** [outl1ne/nova-media-hub#38]
Hello @outl1ne @Tarpsvo ,

how / where do i have to configure that it makes thumbnails and other formats after upload an how to access those afterwards? That documentation is missing.. 

I use S3 as a place to upload with visiblity to public

**Comment by trippo** [comment]
The Media class missing a method like:
```
public function getUrl(string $conversion = null)
    {
        if (!$conversion) {
            return $this->getUrlAttribute();
        }
        if (!isset($this->conversions[$conversion])) {
            return null;
        }

        return Storage::disk($this->conversions_disk)->url($this->conversionsPath . $this->conversions[$conversion]);
    }
    ```

**Comment by Tarpsvo** [comment]
I added ->getUrl($forConversion = null) now. ;)
