### ISSUE TITLE
allowed_mime_types defined for each collection

### ISSUE THREAD

**Issue by trippo** [outl1ne/nova-media-hub#42]
In most situations will be useful to define a different allowed_mime_types array for each collection.

Example: I want a collection only with pdfs

**Comment by richard-raadi** [comment]
@trippo Would you like to open a PR for this? 

We've not really had a situation where it would be required as usually the CMS side of a website is managed by a content-manager or the owner, who decides to use the media hub as they please.

I would like to see you rather define it as a rule for a specific collection, not the allowed_mime_types that checks globally everything that is uploaded.

I'll wait for your reply for 2 weeks and then I'll close the issue 🕦
