### ISSUE TITLE
Show image on index list of resource

### ISSUE THREAD

**Issue by trippo** [outl1ne/nova-media-hub#43]
Is possible to show the resource image on the index list of that resource?

**Comment by ndrez-outl1ne** [comment]
It is possible to show images using the avatar field, which is also displayed in multiple places:

https://nova.laravel.com/docs/4.0/resources/file-fields.html#avatars

You can use the ->thumbnail() method to dynamically return the URL of your chosen media item.

**Comment by richard-raadi** [comment]
Yes it's possible.

You can do how ndrez suggested. 

You can also do a custom resolve on the media hub field, to display only on the index, but that solution can vary depending on different technologies used in your project, or even create a separate Image field to resolve media files only on a resource index.

If you run into any issues with the package however, please open a up a new issues thread.

**Comment by piotrku** [comment]
Hmm..

trying:
```
            MediaHubField::make('Featured Image')
                ->defaultCollection('default')
                ->thumbnail(function ($value, $disk) {
                    return $value
                                ? Storage::disk($disk)->url($value)
                                : null;
                })
                ->rules('required'),

```
and I get:
`Method Outl1ne\NovaMediaHub\Nova\Fields\MediaHubField::thumbnail does not exist`
