### ISSUE TITLE
Issues with casting

### ISSUE THREAD

**Issue by johnpuddephatt** [outl1ne/nova-media-hub#52]
I've encountered a couple of issues with casting. I'm happy to look into solutions but I want to share them to make sure I'm not doing something wrong:

**1. `MediaCast` assume the field is an array, and won't work when `MediaHubField` _doesn't_ have ->multiple() set on it.** 

I guess the options are either to create a second Cast for single media fields, or to have MediaCast check if the field value is an array before retrieving the media. I don't think this should be too hard to resolve!

**2. Using `MediaCast` on my model works on my frontend but seems to break things in Nova:**

- I can add media no problem
- Saving data works; I can see it in the database as expected
- When I edit the entry, the field appears empty

Looking in the network tab at the data Nova is receiving, I think the cast is being applied to the value Nova receives? I've come across this before in another package I was contributing to and have never got it clear in my head, but it feels to me like in general a Nova field would want to access the underlying model value not the cast version? I tried switching to a getter (e.g. getImageAttribute) on my model but this seems to have the same issue.

Am I doing something wrong here? if not how are other people handling image fields without running into problems? There's always the option of manually resolving fields in my controllers but it feels messy.

**Comment by johnpuddephatt** [comment]
For the minute I've created my own cast that looks like the following:

```
namespace App\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Outl1ne\NovaMediaHub\Models\Media;

class NovaMediaLibraryCast implements CastsAttributes
{
 public function get($model, string $key, $value, array $attributes)
    {
        if (is_null($value)) {
            return;
        }

        if (request()->is("nova-api/*")) {
            return $value;
        }

        if (is_array($value)) {
            return Media::whereIn("id", json_decode($value, true))->get();
        } 

        else {
            return Media::find($value);
        }
    }
```

This solves both of the above issues. The bit that checks if it's a /nova-api/ request feels like a hack, but it solves my problem for now.

**Comment by BoiteBeet** [comment]
Another way to fix it is by adding a resolveCallback on the field and returning the rawAttribute without casting.

**Comment by BoiteBeet** [comment]
To add to my answer, you can:
- use this on every field: `->resolveUsing(fn($value, $resource, $attribute) => Arr::get($resource->getRawOriginal(), $attribute))`
- extend the field class and add the method:
```
protected function resolveAttribute($resource, $attribute)
{
    return Arr::get($resource->getRawOriginal(), $attribute);
}
```
