### ISSUE TITLE
MediaHub not showing in menu.

### ISSUE THREAD

**Issue by vmind** [outl1ne/nova-media-hub#58]
Hi,
maybe I have missing something:
Laravel Nova: 4.26
Laravel: 10.14.1

The menu has not been changed so the tool should automatically appear in the main menu.
Also remove all links and leave only the dashboard link... still not appearing.
MediaHubField works in resources but i need this as my main file library.

NovaServiceProvider (\Outl1ne\NovaMediaHub\MediaHub::make())

**Comment by richard-raadi** [comment]
I am not able to reproduce this. 

Do you have any more info?

Did you maybe forget to remove ->hideFromMenu() from NovaServiceProvider?

**Comment by richard-raadi** [comment]
We could not reproduce, if you have any more information to reproduce this then please open up a new issue with more information.
