### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by smilingpeanut** [outl1ne/nova-media-hub#6]
Can this package be used as a interface for `spatie/laravel-medialibrary` or is it otherwise compatible with that way of storing/accessing media?

**Comment by Tarpsvo** [comment]
Hi! I initially experimented with using `spatie/laravel-medialibrary` as a backend, but it was too limiting as it would disallow using the media hub package in a lot of my usecases in Nova.

You could theoretically work around this by overwriting ->fillUsing() and ->resolveUsing() functions for the MediaHub field, but I don't think it's worth it. It's easier to use some alternative Nova package that uses `spatie/laravel-medialibrary` as a backend.
