### ISSUE TITLE
Button break style after 4.28

### ISSUE THREAD

**Issue by murdercode** [outl1ne/nova-media-hub#69]
### Laravel Nova 4.28
![acda5e2d-c34d-4946-9874-a364f465c7d6](https://github.com/outl1ne/nova-media-hub/assets/7630252/bac1e240-8d7e-4849-a069-fa50faec4453)

### Laravel Nova 4.27
![Screenshot 2023-10-26 alle 11 05 52](https://github.com/outl1ne/nova-media-hub/assets/7630252/8f4db02d-1d50-45a9-8c5e-c9493e435bcc)

**Comment by BoiteBeet** [comment]
Nova remove the "LoadingButton" from the components and created a seperate js package called "laravel-nova-ui" with a single Button component in it. To fix it, you can simply create a package with "artisan nova:asset" and copy-paste the LoadingButton from a previous version. I made myself a package for that and you are free to use it to fix the problem in the meantime [laravel-nova-ui-fix](https://packagist.org/packages/boitebeet/laravel-nova-ui-fix)

**Comment by Tarpsvo** [comment]
Heya guys! Sorry for the delay. I fixed the buttons in version 1.7.2 now. ;)
