### ISSUE TITLE
Cannot save if the field is multiple and submitted 0 image

### ISSUE THREAD

**Issue by she-kelvin** [outl1ne/nova-media-hub#71]
I have a MediaHubField that has the property multiple. When I try to save the item, it show the following error : 
 count(): Argument #1 ($value) must be of type Countable|array, null given {"userId":1,"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, null given at /code/code/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1095)

I tried to add an image and it success to save. How can I make it possible to be nullable when it is multiple.

**Comment by Tarpsvo** [comment]
Heya! PR #64 hopefully addressed this issue and it should no longer crash in version 1.8.0.
