### ISSUE TITLE
Empty field issue

### ISSUE THREAD

**Issue by Brand3000** [outl1ne/nova-media-hub#73]
Hi! Could you give me a clue please? If a field is empty, I can't save a resource. 
The details: I have a field:
`MediaHubField::make('Top slider photos', 'slider')->multiple(),`
then I have a cast:
`'slider' => \Outl1ne\NovaMediaHub\Casts\MediaCast::class,`

If I choose some photos everything works fine. But if I just save a resource with empty field, I get the next error:
local.ERROR: count(): Argument #1 ($value) must be of type Countable|array, null given

**Comment by Tarpsvo** [comment]
Heya! I believe PR #64 addresses this issue. Please see if version 1.8.0 made a difference. Thanks!
