### ISSUE TITLE
Is it possible to add image externally?

### ISSUE THREAD

**Issue by she-kelvin** [outl1ne/nova-media-hub#77]
I have a frontend that allow user to upload image to the server and insert to the related model with mediahub field. Is it possible to add the image to the media_hub table so the media hub field can use them in the nova backend?

**Comment by NessterGit** [comment]
If you mean add the image itself to the database table, I don't think so, and not advisable. 

What I would do, if possible in your situation, is make an API route to handle the file upload request and use MediaHub's fileHandler to register the image. Like so:
```
$uploadedImage = MediaHub::fileHandler()            
                    ->withFile($fileToUpload)
                    ->withCollection('YOUR-COLLECTION')
                    ->save();
```

There are other options for the fileHandler, look up the code, it's well written and easy to navigate. 
Happy coding,

**Comment by Tarpsvo** [comment]
Heya! @NessterGit is correct! You can do `MediaHub::fileHandler()->save($file)` where the $file is RemoteFile/UploadedFile/SymfonyFile/Base64File or a local filesystem (ie temp) path to the file. :)
