### ISSUE TITLE
Spatie/image bump to V3

### ISSUE THREAD

**Issue by Jaspur** [outl1ne/nova-media-hub#78]
Hi, can you bump the version used for Spatie/image to V3 for better Laravel 11 support?  @Tarpsvo

**Comment by Tarpsvo** [comment]
Heya! Version 1.8.0 now uses spatie/image V3. :)

**Comment by Tarpsvo** [comment]
I lied. Had to revert it. Due to a failed composer install, I missed that Manipulations object is now gone and spatie/image v3 requires some major changes. Maybe in 2.0.
