### ISSUE TITLE
Call to a member function authorize() on null

### ISSUE THREAD

**Issue by salarmotevalli** [outl1ne/nova-media-hub#82]
This error occurs when wyOptimizerChain() is used like [here](https://github.com/outl1ne/nova-media-hub?tab=readme-ov-file#installation) in documention

laravel/framework: "^11.0
outl1ne/nova-media-hub: "^2.0"

**Comment by Tarpsvo** [comment]
Heya! Fixed the docs. There was a race-condition issue with loading the ServiceProviders and assuming the tools() to be created when running a non-nova job queue in the background for example. The optimizer chain sadly has to be configured statically in AppServiceProvider. :(
