### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by MA7MOUDAL3RABY** [outl1ne/nova-media-hub#9]
can't install it , i got the follwing error when run composer require outl1ne/nova-media-hub
____________________________________________________________________
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - outl1ne/nova-media-hub[1.0.0, ..., 1.0.2] require outl1ne/nova-translatable 2.0.4 -> found outl1ne/nova-translatable[2.0.4] but the package is fixed to 2.0.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - outl1ne/nova-media-hub[1.0.3, ..., 1.0.5] require spatie/image ^2.2 -> found spatie/image[2.2.0, ..., 2.2.4] but the package is fixed to 1.10.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires outl1ne/nova-media-hub ^1.0 -> satisfiable by outl1ne/nova-media-hub[1.0.0, ..., 1.0.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require outl1ne/nova-media-hub:*" to figure out if any version is installable, or "composer require outl1ne/nova-media-hub:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by vodnicearv** [comment]
update your spatie/image package from 1.10.6 to version 2.2

**Comment by Tarpsvo** [comment]
Seems like you've locked your nova-translatable and spatie/image versions.

**Comment by MA7MOUDAL3RABY** [comment]
thanks all, it has been solved with the following 
" rm -rf vendor/ composer.lock" 
"composer install --ignore-platform-reqs"
